name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Build image
        run: |
          docker build \
            --pull \
            --progress=plain \
            --file Containerfile \
            --tag bluefin-slimbook:test \
            .